import { evaluateMaterial } from './material-rules.ts';

const base = { sourceState: 'in_progress' as const, operator: 'OP-DEMO-01', confirmationTime: '2026-08-25 22:35', lastUpdated: '2026-08-25 22:40' };
export const demoWorkOrders = [
  evaluateMaterial({ ...base, workOrder: 'WO-DEMO-001', fileVersion: 'current', requiredPn: 40, receivedPn: 40, pnDifference: 0, receiptQty: 12500, issueQty: 12500, qtyDifference: 0, shortageCount: 0, extraPnCount: 0, actualReceiptQtyDiffCount: 0, sourceDocumentUrl: '/demo-files/IN_PROGRESS_CURRENT_COMPLETED_WO-DEMO-001.xlsx' }),
  evaluateMaterial({ ...base, workOrder: 'WO-DEMO-002', fileVersion: 'current', requiredPn: 32, receivedPn: 25, pnDifference: 7, receiptQty: 8400, issueQty: 10000, qtyDifference: -1600, shortageCount: 0, extraPnCount: 0, actualReceiptQtyDiffCount: 0, sourceDocumentUrl: '/demo-files/IN_PROGRESS_CURRENT_PENDING_WO-DEMO-002.xlsx' }),
  evaluateMaterial({ ...base, workOrder: 'WO-DEMO-003', fileVersion: 'current', requiredPn: 55, receivedPn: 53, pnDifference: 2, receiptQty: 21000, issueQty: 21000, qtyDifference: 0, shortageCount: 2, extraPnCount: 0, actualReceiptQtyDiffCount: 0, sourceDocumentUrl: '/demo-files/IN_PROGRESS_CURRENT_SHORTAGE_WO-DEMO-003.xlsx' }),
  evaluateMaterial({ ...base, workOrder: 'WO-DEMO-004', fileVersion: 'current', requiredPn: 28, receivedPn: 28, pnDifference: 0, receiptQty: 9500, issueQty: 10000, qtyDifference: -500, shortageCount: 0, extraPnCount: 0, actualReceiptQtyDiffCount: 0, sourceDocumentUrl: '/demo-files/IN_PROGRESS_CURRENT_QUANTITY_DIFFERENCE_WO-DEMO-004.xlsx' }),
  evaluateMaterial({ ...base, workOrder: 'WO-DEMO-005', fileVersion: 'current', requiredPn: 47, receivedPn: 47, pnDifference: 0, receiptQty: 16000, issueQty: 16000, qtyDifference: 0, shortageCount: 0, extraPnCount: 0, actualReceiptQtyDiffCount: 2, sourceDocumentUrl: '/demo-files/IN_PROGRESS_CURRENT_ACTUAL_QTY_DIFFERENCE_WO-DEMO-005.xlsx' }),
  evaluateMaterial({ ...base, workOrder: 'WO-DEMO-006', fileVersion: 'legacy', requiredPn: 18, receivedPn: 18, pnDifference: 0, receiptQty: 6800, issueQty: 6800, qtyDifference: 0, shortageCount: 0, extraPnCount: 1, sourceDocumentUrl: '/demo-files/IN_PROGRESS_LEGACY_EXTRA_PN_WO-DEMO-006.xlsx' }),
  evaluateMaterial({ ...base, workOrder: 'WO-DEMO-007', fileVersion: 'legacy', sourceState: 'archived', operator: null, confirmationTime: null, requiredPn: 12, receivedPn: 12, pnDifference: 0, receiptQty: 4200, issueQty: 4200, qtyDifference: 0, shortageCount: 0, extraPnCount: 0, sourceDocumentUrl: '/demo-files/ARCHIVED_LEGACY_MISSING_METADATA_WO-DEMO-007.xlsx' }),
];
